# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/my-Tools',
                'doc_host': 'https://avivleemann.github.io',
                'git_url': 'https://github.com/avivleemann/my-Tools',
                'lib_path': 'my_Tools'},
  'syms': {'my_Tools.core': {'my_Tools.core.foo': ('core.html#foo', 'my_Tools/core.py')}}}
